# .rubocop.yml
require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb
Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile
Metrics/MethodLength:
  Exclude:
    - bin/helpers/docker.rb
    - app/controllers/demo_controller.rb
Lint/UselessAssignment:
  Exclude:
    - bin/helpers/puma.rb
    - bin/helpers/sidekiq.rb
Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

Rails:
  Enabled: false
