version: "3"
services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pizza-app
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3001:3000"
    env_file:
      - '.env'
    depends_on:
      - db
volumes:
  postgres:
  bundler_gems:
