default: &default
  adapter:  postgresql
  host:     <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port:     <%= ENV['DB_PORT'] || 5432 %>
  pool:     <%= ENV['DB_POOL'] || 5 %>
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  sslmode: disable

development:
  <<: *default
  database: pizza_app_development

test:
  <<: *default
  database: pizza_app_test

staging:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'pizza_app_staging' %>

sandbox:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'pizza_app_sandbox' %>

preprod:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'pizza_app_preprod' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'pizza_app_production' %>
