name: Tests - Backend

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      pizza-database:
        image: postgres:12.6-alpine
        env:
          POSTGRES_DB: pizza_app_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: 
          - 5432:5432

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Setup Database
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/pizza_app_test"
        run: |
          bin/rails db:create
          bin/rails db:migrate    

      - name: Run Backend Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/pizza_app_test"
        continue-on-error: false
        run: bundle exec rspec -f documentation --parallel
