name: Tests - Pull Request


on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3-alpine
        volumes:
          - postgres:/var/lib/postgresql/data
        ports:
          - 5434:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and Run Docker Compose
        run: docker-compose up -d --build

      - name: Wait for Database
        run: |
          sleep 15
          docker-compose exec -T db sh -c 'while ! pg_isready -q -h localhost -U postgres; do sleep 1; done'

      - name: Set up Rails Application
        run: docker-compose exec -T web bundle exec rails db:prepare

      - name: Run RSpec Tests
        run: docker-compose exec -T web bundle exec rspec
