name: Tests - Backend

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      pizza-database:
        image: postgres:12.6-alpine
        env:
          POSTGRES_DB: pizza_app_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DB_HOST: 127.0.0.1
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --cpu-shares=512

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set without 'development'
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Setup Database
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/pizza_app_test"
        run: |
          bundle exec rake db:test:prepare
          bin/rails db:create db:schema:load

      - name: Run Backend Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/pizza_app_test"
        continue-on-error: false
        run: bundle exec rspec -f documentation
